namespace NoesisGUI.MonoGameWrapper.Helpers
{
    using System.Collections.Generic;
    using System.Runtime.CompilerServices;
    using Microsoft.Xna.Framework.Input;
    using Noesis;

    internal static class KeyConverter
    {
        // ReSharper disable once InconsistentNaming
        private static readonly Dictionary<Keys, Key> noesisKeys;

        static KeyConverter()
        {
            noesisKeys = new Dictionary<Keys, Key>(XnaKeysComparer.Instance)
            {
                { Keys.Back, Key.Back },
                { Keys.Tab, Key.Tab },
                { Keys.Enter, Key.Enter },
                { Keys.Pause, Key.Pause },
                { Keys.CapsLock, Key.CapsLock },
                { Keys.Kana, Key.KanaMode },
                { Keys.Kanji, Key.KanjiMode },
                { Keys.Escape, Key.Escape },
                { Keys.ImeConvert, Key.ImeConvert },
                { Keys.ImeNoConvert, Key.ImeNonConvert },
                { Keys.Space, Key.Space },
                { Keys.PageUp, Key.PageUp },
                { Keys.PageDown, Key.PageDown },
                { Keys.End, Key.End },
                { Keys.Home, Key.Home },
                { Keys.Left, Key.Left },
                { Keys.Up, Key.Up },
                { Keys.Right, Key.Right },
                { Keys.Down, Key.Down },
                { Keys.Select, Key.Select },
                { Keys.Print, Key.Print },
                { Keys.Execute, Key.Execute },
                { Keys.PrintScreen, Key.PrintScreen },
                { Keys.Insert, Key.Insert },
                { Keys.Delete, Key.Delete },
                { Keys.Help, Key.Help },
                { Keys.D0, Key.D0 },
                { Keys.D1, Key.D1 },
                { Keys.D2, Key.D2 },
                { Keys.D3, Key.D3 },
                { Keys.D4, Key.D4 },
                { Keys.D5, Key.D5 },
                { Keys.D6, Key.D6 },
                { Keys.D7, Key.D7 },
                { Keys.D8, Key.D8 },
                { Keys.D9, Key.D9 },
                { Keys.A, Key.A },
                { Keys.B, Key.B },
                { Keys.C, Key.C },
                { Keys.D, Key.D },
                { Keys.E, Key.E },
                { Keys.F, Key.F },
                { Keys.G, Key.G },
                { Keys.H, Key.H },
                { Keys.I, Key.I },
                { Keys.J, Key.J },
                { Keys.K, Key.K },
                { Keys.L, Key.L },
                { Keys.M, Key.M },
                { Keys.N, Key.N },
                { Keys.O, Key.O },
                { Keys.P, Key.P },
                { Keys.Q, Key.Q },
                { Keys.R, Key.R },
                { Keys.S, Key.S },
                { Keys.T, Key.T },
                { Keys.U, Key.U },
                { Keys.V, Key.V },
                { Keys.W, Key.W },
                { Keys.X, Key.X },
                { Keys.Y, Key.Y },
                { Keys.Z, Key.Z },
                { Keys.LeftWindows, Key.LWin },
                { Keys.RightWindows, Key.RWin },
                { Keys.Apps, Key.Apps },
                { Keys.Sleep, Key.Sleep },
                { Keys.NumPad0, Key.NumPad0 },
                { Keys.NumPad1, Key.NumPad1 },
                { Keys.NumPad2, Key.NumPad2 },
                { Keys.NumPad3, Key.NumPad3 },
                { Keys.NumPad4, Key.NumPad4 },
                { Keys.NumPad5, Key.NumPad5 },
                { Keys.NumPad6, Key.NumPad6 },
                { Keys.NumPad7, Key.NumPad7 },
                { Keys.NumPad8, Key.NumPad8 },
                { Keys.NumPad9, Key.NumPad9 },
                { Keys.Multiply, Key.Multiply },
                { Keys.Add, Key.Add },
                { Keys.Separator, Key.Separator },
                { Keys.Subtract, Key.Subtract },
                { Keys.Decimal, Key.Decimal },
                { Keys.Divide, Key.Divide },
                { Keys.F1, Key.F1 },
                { Keys.F2, Key.F2 },
                { Keys.F3, Key.F3 },
                { Keys.F4, Key.F4 },
                { Keys.F5, Key.F5 },
                { Keys.F6, Key.F6 },
                { Keys.F7, Key.F7 },
                { Keys.F8, Key.F8 },
                { Keys.F9, Key.F9 },
                { Keys.F10, Key.F10 },
                { Keys.F11, Key.F11 },
                { Keys.F12, Key.F12 },
                { Keys.F13, Key.F13 },
                { Keys.F14, Key.F14 },
                { Keys.F15, Key.F15 },
                { Keys.F16, Key.F16 },
                { Keys.F17, Key.F17 },
                { Keys.F18, Key.F18 },
                { Keys.F19, Key.F19 },
                { Keys.F20, Key.F20 },
                { Keys.F21, Key.F21 },
                { Keys.F22, Key.F22 },
                { Keys.F23, Key.F23 },
                { Keys.F24, Key.F24 },
                { Keys.NumLock, Key.NumLock },
                { Keys.Scroll, Key.Scroll },
                { Keys.LeftShift, Key.LeftShift },
                { Keys.RightShift, Key.RightShift },
                { Keys.LeftControl, Key.LeftCtrl },
                { Keys.RightControl, Key.RightCtrl },
                { Keys.LeftAlt, Key.LeftAlt },
                { Keys.RightAlt, Key.RightAlt },
                { Keys.BrowserBack, Key.BrowserBack },
                { Keys.BrowserForward, Key.BrowserForward },
                { Keys.BrowserRefresh, Key.BrowserRefresh },
                { Keys.BrowserStop, Key.BrowserStop },
                { Keys.BrowserSearch, Key.BrowserSearch },
                { Keys.BrowserFavorites, Key.BrowserFavorites },
                { Keys.BrowserHome, Key.BrowserHome },
                { Keys.VolumeMute, Key.VolumeMute },
                { Keys.VolumeDown, Key.VolumeDown },
                { Keys.VolumeUp, Key.VolumeUp },
                { Keys.MediaNextTrack, Key.MediaNextTrack },
                { Keys.MediaPreviousTrack, Key.MediaPreviousTrack },
                { Keys.MediaStop, Key.MediaStop },
                { Keys.MediaPlayPause, Key.MediaPlayPause },
                { Keys.LaunchMail, Key.LaunchMail },
                { Keys.SelectMedia, Key.SelectMedia },
                { Keys.LaunchApplication1, Key.LaunchApplication1 },
                { Keys.LaunchApplication2, Key.LaunchApplication2 },
                { Keys.OemSemicolon, Key.OemSemicolon },
                { Keys.OemPlus, Key.OemPlus },
                { Keys.OemComma, Key.OemComma },
                { Keys.OemMinus, Key.OemMinus },
                { Keys.OemPeriod, Key.OemPeriod },
                { Keys.OemQuestion, Key.OemQuestion },
                { Keys.OemTilde, Key.OemTilde },
                //{ Keys.ChatPadGreen, Key.ChatPadGreen },
                //{ Keys.ChatPadOrange, Key.ChatPadOrange },
                { Keys.OemOpenBrackets, Key.OemOpenBrackets },
                { Keys.OemPipe, Key.OemPipe },
                { Keys.OemCloseBrackets, Key.OemCloseBrackets },
                { Keys.OemQuotes, Key.OemQuotes },
                { Keys.Oem8, Key.Oem8 },
                { Keys.OemBackslash, Key.OemBackslash },
                { Keys.ProcessKey, Key.ImeProcessed },
                { Keys.OemCopy, Key.OemCopy },
                { Keys.OemAuto, Key.OemAuto },
                { Keys.OemEnlW, Key.OemEnlw },
                { Keys.Attn, Key.Attn },
                { Keys.Crsel, Key.CrSel },
                { Keys.Exsel, Key.ExSel },
                { Keys.EraseEof, Key.EraseEof },
                { Keys.Play, Key.Play },
                { Keys.Zoom, Key.Zoom },
                { Keys.Pa1, Key.Pa1 },
                { Keys.OemClear, Key.OemClear },
            };
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Key Convert(Keys key)
        {
            return noesisKeys.TryGetValue(key, out var noesisKey) ? noesisKey : Key.None;
        }
    }
}